### ISSUE TITLE
Call failed

### ISSUE THREAD

**Issue by tusharnetset** [voximplant/react-native-demo#38]
After login,In "Call to" section when I enter another user's username It always show "Call Failed:Not found".

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for reaching out!

The issue may be caused by:
1. you have not created VoxEngine scenario or it has issues
2. you have not created Voximplant application rule
3. you have entered invalid Voximplant user name

Please check these possible issues in your Voximplant application configuration.

I also recommend you look at these tutorials that contain some examples:
1. https://voximplant.com/blog/voximplant-p2p-video-chat
2. https://voximplant.com/docs/references/articles/quickstart/apps-scenarios-rules-and-users

Please let me know if you find the root cause of the issue.

Best regards,
Yulia Grigorieva

**Comment by tusharnetset** [comment]
Hello!
Thank you for your response and tutorials that you have given to us.We had
successfully run a video call in your demo.Now we are moving a step ahead
and going to execute this into our project.
In further implementation if we need any help then we will get back to you
soon.

**Comment by YuliaGrigorieva** [comment]
@tusharnetset ,

Glad to know that the issue is resolved.

I'm closing this issue for now. Please open a new one in case of any problems or questions.

Best regards,
Yulia Grigorieva

**Comment by tusharnetset** [comment]
Hi
I am trying to add voximplant npm in react native ios but I am getting this
error again and again
"dyld: Library not loaded: @rpath/CocoaLumberjack.framework/CocoaLumberjack
  Referenced from:
/Users/netset/Library/Developer/CoreSimulator/Devices/617330EF-27D9-42C7-82EE-1DC99A381F05/data/Containers/Bundle/Application/4FACB3CA-A6D8-4E94-BB35-0F863BDAF536/Levelz.app/Frameworks/VoxImplant.framework/VoxImplant
  Reason: image not found"

Can you please help me out into this issue?
(lldb)

**Comment by rAnAaRsl** [comment]
I have followed the instructions but it still shows call failed

**Comment by YuliaGrigorieva** [comment]
Hello, @rAnAaRsl !

Please provide more details about your issue. What error do you receive when you make a call?

Have you checked the following possible issues?
> 1. you have not created VoxEngine scenario or it has issues
> 2. you have not created Voximplant application rule
> 3. you have entered invalid Voximplant user name

Best regards,
Yulia Grigorieva

**Comment by rAnAaRsl** [comment]
I have created VoxEngine scenario which is 

VoxEngine.forwardCallToUserDirect();
VoxEngine.addEventListener(AppEvents.CallAlerting, (e) => {
  const newCall = VoxEngine.callUserDirect(
    e.call, 
    e.destination,
    e.callerid,
    e.displayName,
    null
  );
  VoxEngine.easyProcess(e.call, newCall, ()=>{}, true);
});

And i have Created application rule as well and used a valid Voximplant user name

**Comment by YuliaGrigorieva** [comment]
@rAnAaRsl ,

Thank you for the provided information!
The issue is most likely caused by your scenario that duplicates call processing.
`VoxEngine.forwardCallToUserDirect` is a helper function that do the same thing as listed after this line in your scenario.

Please change your scenario to the following one line scenario:
```
VoxEngine.forwardCallToUserDirect();
```

Please let me know the results.

Best regards,
Yulia Grigorieva

**Comment by rAnAaRsl** [comment]
Issue Resolved thank your for the help

**Comment by reactdevrocks** [comment]
after ringing once on other phone and shows on first phone declined.

**Comment by YuliaGrigorieva** [comment]
Hello @reactdevrocks ,

Please provide your VoxEngine scenario.

Best regards,
Yulia Grigorieva

**Comment by reactdevrocks** [comment]
Hi @YuliaGrigorieva 
this is my scenariao
Thanks

VoxEngine.addEventListener(AppEvents.CallAlerting, e => {
  const newCall = VoxEngine.callUserDirect(
     e.call, 
     e.destination,
     e.callerid,
     e.displayName,
     null
   );
   VoxEngine.easyProcess(e.call, newCall, ()=>{}, true);

});

**Comment by reactdevrocks** [comment]
@YuliaGrigorieva now audio and video call is happening from one ios device only. means if i call from second ios device then it is showing "Call failed: Not Found". (Using above scenario)

**Comment by reactdevrocks** [comment]
@YuliaGrigorieva any solution for above one?

**Comment by YuliaGrigorieva** [comment]
Hello @reactdevrocks ,

"Call failed: Not Found" error means that you call the user that:
1. does not exist (not created in the Voximplant application)
2. routing is not set up in the Voximplant application
3. you enter the user in invalid format

Best regards,
Yulia Grigorieva

**Comment by reactdevrocks** [comment]
but the user from which i am calling to another is getting incoming call but when i do outgoing call it shows "Call failed: Not Found".

1) User is created in Voximplant application with valid formate
  a) first user is - tej.prakash
  b) second user is - pranabesh
so i think both is in valid format

2) routing is also setup in Voximplant application.


![Screenshot 2019-07-16 at 8 47 51 PM](https://user-images.githubusercontent.com/45207346/61307413-e6b15a00-a80b-11e9-91ea-94bfcc388a1a.jpg)

**Comment by reactdevrocks** [comment]
@YuliaGrigorieva i am waiting for clarifying.

**Comment by YuliaGrigorieva** [comment]
Hello @reactdevrocks ,

Please contact us at support@voximplant.com and provide details (your Voximplant account name and Voximplant application), so we can check your setup and give you recommendations.

Best regards,
Yulia Grigorieva

**Comment by reactdevrocks** [comment]
Thanks for reply

ACCOUNT NAME IS : USER NAME: clirnet and email is: tejprakash.tiwari@clirnet.com
APPLICATION NAME IS : clirnet.clirnet.voximplant.com

and also the demo android is not setting up.. i am totally frustrated since two days and looking for another chatting libraries. help me!!

**Comment by YuliaGrigorieva** [comment]
Hello @reactdevrocks ,

I have taken a look at your Voximplant application setup, I do not see any issues. Moreover, I see several successful calls between Voximplant users you have mentioned before.

Do you still observe "Not found" issues? Do you have any other call fail reasons?

Best regards,
Yulia Grigorieva

**Comment by reactdevrocks** [comment]
yes when i call from pranabesh to tej.prakash then it connects successfully and calls happening, but when i do vice versa means tej.prakash to pranabesh then it shows "Call failed: Not Found" and it is not showing in call history.

Thanks

**Comment by YuliaGrigorieva** [comment]
Could you please check that you do not enter any extra whitespaces on the main application screen when you input "pranabesh"?

**Comment by reactdevrocks** [comment]
yes checked that still not happening.

**Comment by rosnaib11** [comment]
@YuliaGrigorieva what about I keep getting "No route to host" 503
